import 'package:economics_app/app/configs/constants.dart';
import 'package:economics_app/diagrams/enums/diagram_bundle_enum.dart';
import 'package:economics_app/home_page/models/slide_content.dart';

import '../../../diagrams/enums/unit_type.dart';
import '../../models/slide.dart' show Slide;

List<Slide> get elasticityDemandSlides => [
  Slide(
    section: Subunit.elasticityDemand,
    title: kKeyTerms,
    contents: [
      SlideContent.term(
        'Price Elasticity of Demand (PED)',
        'measures the responsiveness of the quantity of good demanded to changes in its price. <strong>PED = %∆Qd ÷ %∆P.</strong>',
      ),
      SlideContent.term(
        'Price inelastic demand (PED < 1)',
        'is when a change in price of a good leads to a proportionally smaller change in its quantity demanded. Examples include many necessities like salt, gasoline and rice.',
      ),
      SlideContent.term(
        'Price elastic demand (PED < 1)',
        'is when a change in the price of a good leads to a proportionally larger change in the quantity demanded. Examples includes many generic consumer products, and luxuries such as holidays.',
      ),
      SlideContent.term(
        'Unitary price elastic demand (PED = 1)',
        'is when a change in the price of a good results in the same percentage change in the quantity demanded.',
      ),
      SlideContent.term(
        'Perfectly price inelastic demand (PED = 0)',
        'is when a change in the price of a good has no affect on its quantity demanded. Examples include life-saving medicines',
      ),
      SlideContent.term(
        'Price inelastic demand (PED < 1)',
        'is when any change in the price of a good has an infinitely large change in its quantity demanded. Consumers are extremely sensitive to price changes. Examples include generic goods with perfect substitutes.',
      ),
      SlideContent.term(
        'Total Revenue (TR)',
        'is the total income generated by a firm selling goods and services. <strong>TR = Price X Quantity.</strong>',
      ),
      SlideContent.term(
        'Primary commodity',
        'is a good sold for production or consumption just as it was found in nature.',
      ),
      SlideContent.term(
        'Manufactured Good',
        'is a product that has been processed from raw materials into a finished good.',
      ),
      SlideContent.term(
        'Income Elasticity Of Demand (YED)',
        'measures the responsiveness of demand to a change in income. <strong>%∆Qd ÷ %∆Y.</strong>',
      ),
      SlideContent.term(
        'Luxuries',
        'are normal goods where an increase in income causes a bigger percentage increase in demand. They are typically seen as desirable and prestigious.',
      ),
      SlideContent.term(
        'Necessities',
        'are normal goods where an increase in income causes a smaller percentage increase in demand. They are essential for one’s basic survival and well-being.',
      ),
      SlideContent.term(
        'Engel Curve',
        'is a diagram which illustrates how household expenditure varies with income.',
      ),
      SlideContent.term(
        'Primary sector',
        'involves the extraction and production of raw materials, such as farming, fishing, forestry and mining.',
      ),
      SlideContent.term(
        'Secondary sector',
        'involves the processing and manufacturing of raw materials into finished goods.',
      ),
      SlideContent.term(
        'Tertiary sector',
        'involves the provision of services including banking, healthcare, retail and education.',
      ),
      SlideContent.term(
        'Economically Least-Developed Counties (ELDCs)',
        'are low-income countries which face significant barriers to economic development.',
      ),
    ],
  ),
];
