enum DiagramLabel {
  a,
  b,
  c,
  d,
  e,
  f,
  g,
  h,
  i,
  consumerSurplus,
  producerSurplus,
  consumerBurden,
  producerBurden,
  abnormalProfit,
  socialWelfare,
  welfareLoss,
  loss,
  tablets,
  phones,
  soccerBalls,
  volleyBalls,
  pPC1,
  pPC2,
  s,
  sTax,
  sSub,
  sm,
  sme,
  sm1,
  sm2,
  dm,
  dme,
  dm1,
  dm2,
  s1,
  d1,
  demand,
  dMarket,
  dEqualsMB,
  dL,
  supply,
  s2,
  s3,
  sEqualsMC,
  sL,
  product,
  totalProduct,
  marginalProduct,
  increasingReturns,
  diminishingReturns,
  diminishingReturnsSetIn,
  negativeReturns,
  marginalCost,
  input,
  costs,
  d2,
  d3,
  p,
  price,
  priceCostsBenefits,
  price$,
  pD,
  p1,
  p2,
  p3,
  pc,
  pp,
  pSub,
  priceCeiling,
  priceFloor,
  surplusLabor,
  pf,
  wageRate,
  nmw,
  q,
  quantityOfChocolateBars,
  q1,
  q2,
  q3,
  q4,
  qpi,
  pe,
  we,
  pme,
  qe,
  qTax,
  qSub,
  qS,
  qD,
  qSStar,
  qDStar,
  quantityOfLabor,
  quantityUnits,
  pM,
  elasticDemand,
  unitElasticDemand,
  inelasticDemand,
  pedSmaller1,
  pedBigger1,
  pedEqual1,
  income,
  normalGoodNecessity,
  normalGoodLuxury,
  inferiorGood,
  revenueUnchanged,
  shortage,
  shortageQdMinusQs,
  surplus,
  surplusQsMinusQd,
  surplusLaborUnemployment,
  governmentBoughtSurplusQsMinusQd,
  governmentPurchases,
  priceFloorAgri,
  freeMarket,
  sociallyOptimumOutput,
  dEqualsMPB,
  dEqualsMPBMSB,
  sEqualsMPC,
  sEqualsMPCMSC,
  mPCPlusSubsidy,
  externality,
  externalBenefits,
  externalCost,
  externalCostOfOverFishing,
  mpc,
  msc,
  msb,
  pOpt,
  pm,
  pm1,
  pm2,
  qOpt,
  qm,
  pPEqualsPOpt,
  mscEqualsMPCPlusTax,
  pigouvianTaxEqualsExternalCost,
  subsidyEqualExternalBenefits,
  governmentDirectProvision,
  mscEqualsMPCPlusSubsidy,
  mscEqualsMPCPlusGovernmentProvision,
  revenue,
  priceCostsRevenue,
  industryQuantity,
  quantity,
  quantityFirm,
  dEqualsARMR,
  dEqualsAR,
  d1EqualsAR1MR1,
  mr,
  mc,
  atc,
  srac,
  lrac,
  mcEqualsMR,
  mscPlusRegulations,
  governmentRegulations,
  goodA,
  goodB,
  sD,
  sDQ,
  sDSub,
  dD,
  sW,
  households,
  firms,
  factorsOfProduction,
  factorPayments,
  landLaborCapitalEnterprise,
  householdSpending,
  householdSpendingFirmRevenue,
  goodsAndServices,
  leakages,
  injections,
  rentWagesInterestProfit,
  factorMarkets,
  productMarkets,
  government,
  society,
  financialSector,
  foreignSector,
  tax,
  governmentTaxRevenue,
  taxes,
  governmentBudget,
  savings,
  investment,
  interestRate,
  quantityOfMoney,
  sM,
  dM,
  sM1,
  sM2,
  imports,
  exports,
  monetaristsNewClassical,
  keynesian,
  priceLevel,
  realGDP,
  potentialOutput,
  timeYears,
  aggregateDemand,
  aD,
  aD1,
  aD2,
  aD3,
  inflationRate,
  unemploymentRate,
  sRPC,
  lRPC,
  aggregateSupply,
  keynesianAS,
  aS,
  shortRunAggregateSupply,
  sRAS,
  longRunAggregateSupply,
  lRAS,
  pL,
  yF,
  yE,
  yInf,
  yDef,
  cheese,
  wineBottles,
  dW,
  dS,
  sWT,
  sWQ,
  pW,
  pWT,
  pWQ,
  pWS,
  euroPerDollar,
  quantityOfUSD,
  qUSD,
  supplyOfUSD,
  demandForUSD,
  euroUSD,
  eR,
  eR1,
  eR2,
  eRF,
  ninety,
  ninetyFive,
  oneHundredAndFive,
  exchangeRate,
  quantityOfCurrency,
  upperBand,
  lowerBand,
  tradeBalance,
  tradeSurplus,
  tradeDeficit,
  tradeBalanced,
  time,
  lowIncome,
  lowSavings,
  lowInvestment,
  lowProductivity,
  depreciationDevaluation,
}

extension MicroLabelExtension on DiagramLabel {
  String get label {
    return switch (this) {
      DiagramLabel.p => 'P',
      DiagramLabel.q => 'Q',
      DiagramLabel.pe => 'Pe',
      DiagramLabel.qe => 'Qe',
      DiagramLabel.d => 'D',
      DiagramLabel.d1 => 'D₁',
      DiagramLabel.s => 'S',
      DiagramLabel.s1 => 'S₁',
      DiagramLabel.p1 => 'P₁',
      DiagramLabel.p2 => 'P₂',
      DiagramLabel.p3 => 'P₃',
      DiagramLabel.q1 => 'Q₁',
      DiagramLabel.q2 => 'Q₂',
      DiagramLabel.q3 => 'Q₃',
      DiagramLabel.q4 => 'Q₄',

      DiagramLabel.s2 => 'S₂',
      DiagramLabel.d2 => 'D₂',

      DiagramLabel.dEqualsMPBMSB => 'D=MPB=MSB',
      DiagramLabel.mpc => 'S=MPC',
      DiagramLabel.qS => 'Qs',
      DiagramLabel.qD => 'Qd',
      DiagramLabel.pM => 'Pᴹ',

      DiagramLabel.shortage => 'Shortage',
      DiagramLabel.surplus => 'surplus',
      DiagramLabel.msc => 'MSC',
      DiagramLabel.pOpt => 'Popt',
      DiagramLabel.pm => 'Pm',

      DiagramLabel.dEqualsMPB => 'D=MPB',
      DiagramLabel.qOpt => 'Qopt',
      DiagramLabel.qm => 'Qm',
      DiagramLabel.priceCostsRevenue => 'Price,\nCosts,\nRevenues\n(\$)',
      DiagramLabel.quantityFirm => 'Quantity - Firm',
      DiagramLabel.d1EqualsAR1MR1 => 'D₁=AR₁=MR₁',
      DiagramLabel.dEqualsARMR => 'D=AR=MR',
      DiagramLabel.mr => 'MR',
      DiagramLabel.mc => 'MC',
      DiagramLabel.msb => 'MSB',
      DiagramLabel.atc => 'ATC',
      DiagramLabel.srac => 'SRAC',
      DiagramLabel.mcEqualsMR => 'MC=MR',
      DiagramLabel.tablets => 'Tablets',
      DiagramLabel.phones => 'Phones',
      DiagramLabel.soccerBalls => 'Soccer Balls',
      DiagramLabel.volleyBalls => 'Volley Balls',

      DiagramLabel.sEqualsMPC => 'S=MPC',

      DiagramLabel.sEqualsMPCMSC => 'S=MPC=MSC',

      DiagramLabel.sm => 'Sm',
      DiagramLabel.dm => 'Dm',
      DiagramLabel.industryQuantity => 'Quantity - Industry',
      DiagramLabel.pm1 => 'Pm₁',
      DiagramLabel.dm1 => 'Dm₁',

      DiagramLabel.sm1 => 'Sm₁',
      DiagramLabel.sm2 => 'Sm₂',
      DiagramLabel.dm2 => 'Dm₂',
      DiagramLabel.pm2 => 'Pm₂',
      DiagramLabel.sme => 'Dmₑ',
      DiagramLabel.dme => 'Smₑ',

      DiagramLabel.pme => 'Pmₑ',
      DiagramLabel.consumerSurplus => 'Consumer Surplus',
      DiagramLabel.producerSurplus => 'Producer Surplus',
      DiagramLabel.abnormalProfit => 'Abnormal Profit',
      DiagramLabel.loss => 'Loss',
      DiagramLabel.dEqualsAR => 'D=AR',
      DiagramLabel.quantity => 'Quantity',
      DiagramLabel.lrac => 'LRAC',
      DiagramLabel.welfareLoss => 'Welfare Loss',
      DiagramLabel.externality => 'Externality',
      DiagramLabel.qpi => 'Qπ',
      DiagramLabel.sTax => 'S+Tax',
      DiagramLabel.pc => 'Pc',
      DiagramLabel.pp => 'Pp',
      DiagramLabel.sSub => 'S+Sub',
      DiagramLabel.qTax => 'QTax',
      DiagramLabel.qSub => 'QSub',
      DiagramLabel.sD => 'Sd',
      DiagramLabel.dD => 'Dd',
      DiagramLabel.sW => 'Sw',
      DiagramLabel.pW => 'Pw',
      DiagramLabel.pWT => 'Pw+t',
      DiagramLabel.sWT => 'Sw+t',
      DiagramLabel.sWQ => 'Sw+q',
      DiagramLabel.pWQ => 'Pw+q',
      DiagramLabel.sDQ => 'Sd+q',
      DiagramLabel.sDSub => 'Sd+sub',
      DiagramLabel.pSub => 'P+Sub',
      DiagramLabel.pWS => 'PW+Sub',
      DiagramLabel.pD => 'Pd',
      DiagramLabel.goodA => 'Good A',
      DiagramLabel.goodB => 'Good B',
      DiagramLabel.euroPerDollar => 'Euro € per USD \$',
      DiagramLabel.quantityOfUSD => 'Qty of USD \$',
      DiagramLabel.supplyOfUSD => 'Supply of USD \$',
      DiagramLabel.demandForUSD => 'Demand for USD \$',
      DiagramLabel.eR1 => 'ER₁',
      DiagramLabel.eR2 => 'ER₂',
      DiagramLabel.eR => 'ER',
      DiagramLabel.euroUSD => '€ per \$',
      DiagramLabel.qUSD => 'Q of \$',
      DiagramLabel.ninety => '0.90',
      DiagramLabel.ninetyFive => '0.95',
      DiagramLabel.oneHundredAndFive => '1.05',
      DiagramLabel.exchangeRate => 'Exchange Rate',
      DiagramLabel.quantityOfCurrency => 'Qty of Currency',
      DiagramLabel.eRF => 'ERf',
      DiagramLabel.lowIncome => 'low Income',
      DiagramLabel.lowSavings => 'Low Savings',
      DiagramLabel.lowInvestment => 'Low Investment',
      DiagramLabel.lowProductivity => 'Low Productivity',
      DiagramLabel.tradeBalance => 'Trade Balance',
      DiagramLabel.tradeSurplus => 'Trade\nSurplus\nX > M',
      DiagramLabel.tradeDeficit => 'Trade\nDeficit\nX < M',
      DiagramLabel.tradeBalanced => 'X = M',
      DiagramLabel.time => 'Time',
      DiagramLabel.depreciationDevaluation =>
        'Depreciation\n'
            ' / Devaluation',
      DiagramLabel.a => 'A',
      DiagramLabel.b => 'B',
      DiagramLabel.c => 'C',
      DiagramLabel.upperBand => 'Upper Band',
      DiagramLabel.lowerBand => 'Lower Band',
      DiagramLabel.households => 'Households',
      DiagramLabel.firms => 'Firms',
      DiagramLabel.factorMarkets => 'Factor Markets',
      DiagramLabel.productMarkets => 'Product Markets',
      DiagramLabel.government => 'Government',
      DiagramLabel.financialSector => 'Financial Sector',
      DiagramLabel.foreignSector => 'Foreign Sector',
      DiagramLabel.taxes => 'Taxes',
      DiagramLabel.governmentBudget => 'Government Budget',
      DiagramLabel.savings => 'Savings',
      DiagramLabel.investment => 'Investment',
      DiagramLabel.imports => 'Imports',
      DiagramLabel.exports => 'Exports',
      DiagramLabel.landLaborCapitalEnterprise =>
        'Factors of Production (Land, Labor, Capital, Enterprise)',
      DiagramLabel.householdSpendingFirmRevenue =>
        'Household Spending / Firm Revenue',
      DiagramLabel.goodsAndServices => 'Goods & Services',
      DiagramLabel.rentWagesInterestProfit =>
        'Factor Payments (Rent, Wages, Interest, Profit)',
      DiagramLabel.factorsOfProduction => 'Factors of Production',
      DiagramLabel.factorPayments => 'Factor Payments',
      DiagramLabel.householdSpending => 'Household Spending',
      DiagramLabel.leakages => 'Leakages',
      DiagramLabel.injections => 'Injections',
      DiagramLabel.priceLevel => 'Price Level',
      DiagramLabel.realGDP => 'Real GDP',
      DiagramLabel.aggregateDemand => 'Aggregate Demand',
      DiagramLabel.aD => 'AD',
      DiagramLabel.aggregateSupply => 'AS',
      DiagramLabel.aS => 'AS',
      DiagramLabel.shortRunAggregateSupply => 'Short-Run Aggregate Supply',
      DiagramLabel.sRAS => 'SRAS',
      DiagramLabel.longRunAggregateSupply => 'Long-Run Aggregate Supply',
      DiagramLabel.lRAS => 'LRAS',
      DiagramLabel.pL => 'PL', // Common Y-axis label in AD/AS diagrams
      DiagramLabel.yF => 'Yf', // Full capacity output
      DiagramLabel.yInf => 'Yinf', // Output beyond full employment
      DiagramLabel.yDef => 'Ydef', // Output below full employment
      DiagramLabel.keynesianAS => 'Keynesian AS',
      DiagramLabel.monetaristsNewClassical => 'Monetarist/New Classical Model',
      DiagramLabel.keynesian => 'Keynesian Model',
      DiagramLabel.aD1 => 'AD1',
      DiagramLabel.aD2 => 'AD2',
      DiagramLabel.aD3 => 'AD3',
      DiagramLabel.interestRate => 'Interest Rate',
      DiagramLabel.quantityOfMoney => 'Quantity of Money',
      DiagramLabel.sM => 'Sm',
      DiagramLabel.dM => 'Dm',
      DiagramLabel.sM1 => 'Sm1',
      DiagramLabel.sM2 => 'Sm2',
      DiagramLabel.inflationRate => 'Inflation Rate',
      DiagramLabel.unemploymentRate => 'Unemployment Rate',
      DiagramLabel.lRPC => 'LRPC',
      DiagramLabel.potentialOutput => 'Potential Output',
      DiagramLabel.timeYears => 'Time (Years)',
      DiagramLabel.price => 'Price',
      DiagramLabel.sRPC => 'SRPC',
      DiagramLabel.yE => 'Ye',
      DiagramLabel.e => 'E',
      DiagramLabel.pPC1 => 'PPC1',
      DiagramLabel.pPC2 => 'PPC2',
      DiagramLabel.demand => 'Demand',
      DiagramLabel.d3 => 'D3',
      DiagramLabel.supply => 'Supply',
      DiagramLabel.s3 => 'S3',
      DiagramLabel.price$ => 'Price\n(\$)',
      DiagramLabel.quantityOfChocolateBars => 'Quantity (units)',
      DiagramLabel.dMarket => 'D (Market)',
      DiagramLabel.dW => 'Dw',
      DiagramLabel.dS => 'Sw',
      DiagramLabel.cheese => 'Cheese\n',
      DiagramLabel.wineBottles => 'Wine\n',
      DiagramLabel.product => 'Product',
      DiagramLabel.totalProduct => 'Total Product',
      DiagramLabel.marginalProduct => 'Marginal Product',
      DiagramLabel.increasingReturns => 'Increasing Returns',
      DiagramLabel.diminishingReturns => 'Diminishing Returns',
      DiagramLabel.negativeReturns => 'Negative Returns',
      DiagramLabel.input => 'Input',
      DiagramLabel.costs => 'Costs',
      DiagramLabel.diminishingReturnsSetIn => 'Diminishing Returns Set In',
      DiagramLabel.marginalCost => 'Marginal Cost',
      DiagramLabel.income => 'Income',
      DiagramLabel.normalGoodNecessity => 'Normal Good - Necessity',
      DiagramLabel.normalGoodLuxury => 'Normal Good - Luxury',
      DiagramLabel.inferiorGood => 'Inferior Good',
      DiagramLabel.revenue => 'Revenue',
      DiagramLabel.elasticDemand => 'Elastic Demand\n     (PED > 1)',
      DiagramLabel.unitElasticDemand => 'Unit Elastic Demand\n     (PED = 1)',
      DiagramLabel.inelasticDemand => 'Inelastic Demand\n      (PED < 1)',
      DiagramLabel.revenueUnchanged => 'Revenue',
      DiagramLabel.pedSmaller1 => 'PED<1',
      DiagramLabel.pedBigger1 => 'PED>1',
      DiagramLabel.pedEqual1 => 'PED=1',
      DiagramLabel.pf => 'Pf',
      DiagramLabel.wageRate => 'Wage Rate',
      DiagramLabel.quantityOfLabor => 'Quantity of labor',
      DiagramLabel.nmw => 'NMW',
      DiagramLabel.dEqualsMB => 'D=MB',
      DiagramLabel.sEqualsMC => 'S=MC',
      DiagramLabel.dL => 'DL',
      DiagramLabel.sL => 'SL',
      DiagramLabel.f => 'F',
      DiagramLabel.g => 'G',
      DiagramLabel.h => 'H',
      DiagramLabel.i => 'I',
      DiagramLabel.quantityUnits => 'Quantity (Units)',
      DiagramLabel.tax => 'Tax',
      DiagramLabel.society => 'Society',
      DiagramLabel.consumerBurden => 'Consumer Burden',
      DiagramLabel.producerBurden => 'Producer Burden',
      DiagramLabel.socialWelfare => 'Social Welfare',
      DiagramLabel.shortageQdMinusQs => 'Shortage (Qd - Qs)',
      DiagramLabel.surplusQsMinusQd => 'Surplus (Qs - Qd)',
      DiagramLabel.we => 'We',
      DiagramLabel.surplusLaborUnemployment => 'Surplus Labor (Unemployment)',
      DiagramLabel.qSStar => 'Qs*',
      DiagramLabel.qDStar => 'Qd*',
      DiagramLabel.governmentBoughtSurplusQsMinusQd =>
        'Government-Bought Surplus (Qs - Qd)',
      DiagramLabel.governmentPurchases => 'Government Purchases',
      DiagramLabel.freeMarket => 'Free Market',
      DiagramLabel.priceFloorAgri => 'Price Floor (Agri.)',
      DiagramLabel.externalBenefits => 'External Benefits',
      DiagramLabel.externalCost => 'External Cost',
      DiagramLabel.sociallyOptimumOutput => 'Socially Optimum Output',
      DiagramLabel.priceCeiling => 'Price Ceiling',
      DiagramLabel.priceFloor => 'Price Floor',
      DiagramLabel.surplusLabor => 'Surplus Labor',
      DiagramLabel.pPEqualsPOpt => 'Pp=POpt',
      DiagramLabel.mscEqualsMPCPlusTax => 'MSC=MPC+Tax',
      DiagramLabel.pigouvianTaxEqualsExternalCost =>
        'Pigouvian Tax\n= External Cost',
      DiagramLabel.mscPlusRegulations => 'MSC=MPC+\nRegulations',
      DiagramLabel.governmentRegulations => 'Government\nRegulations',
      DiagramLabel.externalCostOfOverFishing =>
        'External Cost of\nOver-Fishing',
      DiagramLabel.governmentTaxRevenue => 'Government\nTax Revenue',
      DiagramLabel.mscEqualsMPCPlusSubsidy => 'MSC\n=MPC+Subsidy',
      DiagramLabel.subsidyEqualExternalBenefits =>
        'Subsidy =\nExternal Benefits',
      DiagramLabel.priceCostsBenefits => 'Price,\nCosts,\nBenefits',
      DiagramLabel.governmentDirectProvision => 'Government\nDirect Provision',
      DiagramLabel.mscEqualsMPCPlusGovernmentProvision =>
        'MSC=MPC\n+Government\nProvision',
      DiagramLabel.mPCPlusSubsidy => 'MPC+Subsidy',
    };
  }
}
