enum DiagramBundleEnum {
  microPPCConstantOppCost,
  microPPCIncreaseOppCost,
  microDemandPriceChange,
  microDemandIndividual1,
  microDemandIndividual2,
  microDemandMarket,
  microDemandIndividualVsMarket,
  microDemandDeterminants,
  microSupplyPriceChanges,
  microSupplyDeterminants,
  globalWorldPrice,
  globalWorldPriceStandAlone,
  globalNetExporter,
  globalNetImporter,
  globalTariff,
  globalTariffWelfare,
  globalTariffConsumerSurplus,
  globalTariffConsumerSurplusChange,
  globalTariffProducerSurplus,
  globalTariffProducerSurplusChange,
  globalTariffWelfareLoss,
  globalTariffGovernmentRevenue,
}

